<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="TUnit" Version="1.*" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SchedulePlanner.Core\SchedulePlanner.Core.csproj" />
    <ProjectReference Include="..\SchedulePlanner.Wpf\SchedulePlanner.Wpf.csproj" />
    <ProjectReference Include="..\SchedulePlanner.ImportExport\SchedulePlanner.ImportExport.csproj" />
    <ProjectReference Include="..\SchedulePlanner.Worker\SchedulePlanner.Worker.csproj" />
    <ProjectReference Include="..\SchedulePlanner.Cli\SchedulePlanner.Cli.csproj" />
  </ItemGroup>

</Project>
