<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
    <UseMSTest>true</UseMSTest>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="TUnit" Version="1.*" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SchedulePlanner.Worker\SchedulePlanner.Worker.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.8.0" />
  </ItemGroup>

</Project>
