<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Temporalio" Version="1.12.0" />
    <PackageReference Include="Temporalio.Extensions.Hosting" Version="1.12.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SchedulePlanner.Core\SchedulePlanner.Core.csproj" />
    <ProjectReference Include="..\SchedulePlanner.ImportExport\SchedulePlanner.ImportExport.csproj" />
  </ItemGroup>

</Project>