<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="TUnit" Version="1.*" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SchedulePlanner.Cli\SchedulePlanner.Cli.csproj" />
  </ItemGroup>

</Project>
