<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CsvHelper" Version="33.1.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration" Version="10.0.3" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.3" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.3" />
    <PackageReference Include="Microsoft.Extensions.Logging.Console" Version="10.0.3" />
    <PackageReference Include="Microsoft.Extensions.Logging.Debug" Version="10.0.3" />
    <PackageReference Include="System.IO.Abstractions" Version="22.1.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SchedulePlanner.Core\SchedulePlanner.Core.csproj" />
  </ItemGroup>

</Project>
